language: java
install: ./gradlew clean jar
script: ./gradlew check
jdk:
  - oraclejdk8

env:
  global:
    - PGP_KEY_ID="2887CE9B"
    - PGP_PASSWORD=""
    - PGP_SECRET_KEY_RING_FILE=~/.gnupg/secring.gpg
      # NEXUS_USERNAME
    - secure: "Wu9M0ganmgpkBNO1QD4jDHyagWrvm7+2dvNsyDGx9qva2C6xHNVpCtpQ1vFPDTAI76wAv0Yfz8iHVmlMsvJjMfImtip2dVUq+aYK86jEDh4ENfA5uNfjyuTvDRa/cFF+Qm+ml+85IFfWBOo5sCOueX1iKfOsCUETlTjvDCapYkfu728TSnmDGV0R/sNUHi0Mtp4RddWdg4QwOlvqSLBIdh1Y0LFZ1fjQtELcheFZV5MNjXT7t8EbCrqXdu+yaLrr5jm8lNvS+8eMTiZtZ9doUtbiFRbNLc5QAORs4gWo8A3iliCC/wEKNCixa8IlsYM1X1cN77tdSZQwV/zSUutMqwjwYWNl6+BQYPZmGWz1HDIVOhB1b6xiB1C/msLNoQE5OyhqxWGbR18YvqVkwQ3e6kfBw62UlK0CS1ia5mg03GnIyuPQLwOjyYRePmsKyj49MjjmqdZYaU+qoRiOsKRb2+yWjpbOtLcK8SI7a9OdINO+gWQfnPBaiZfRuUClo4Trs6UrJtwiS+5ZdoRsMvuaK/IYPvfCbd3J8ehycjlzDeeCeAs9tICMzGbnfRtgsId4cOAUY6GWoauedPE+3eBVcw1YFZEmcaw1odyzvrR+akiHhPIyM8t1TZogNDZpBUmw0LMEJ1Z32h4acvcX1PKtkiXPMm72tHebR6K43wO1vZ0="
      # NEXUS_PASSWORD
    - secure: "Ig9xlLZYs/ZEc3otw5JXyfMeSuYYl3w/MMm16IF+8p1KZaD3cd5ipQHzUDBVKLGqbl+G5Itiis5M5DFMmFXkmvgrY7kB9Ex79NtGMXv9/JOtR9SZmDsWnJr030z/Bv/AWrmy7t6L6GWTEIyUV8grKNqSiGLEJpavpqUFGC7JGSJZ8s6xexz91dkbeGEsG1KQlHZ9iNuna6opJfoOJdxiodT+uZJkwDG2opAk1jeenvnjQ2S2eBzv2vB+HtjJmjrF9DxYsKl9mJIcITPWtgU8R0zrqG5zFaI1GTiyCnQxwkjcFjc89BDLDI8o9TqqEAN2N9gMQAwtAJd8DhuPpKggbcadPxUFvHF2YUt/djRAdJy+bw4KYVPI5ph7rEw/yvmip3izO6yjCbUp7xh5mzCuMXV1LwAzLExcY3OlamPwUlB92lf7TTWmBjPKKe/GCo0/lQm++uiIxHzVNiSVdp6IrTZAzj5RThU6RsrlFi57mTWesRxXSNSmQ9lOx051I0DUBXioo+xAzjIStujTMrAULf3sj0FvrmEh5mh0tt1LSCFCotJgccidT+76hn9Dpaspmdkgu3dVVN/z+sKTFeZTAL8w6RVrdc3ovvKIRIkYk6EzOHPD4/L5iQztlVlr4ab8yFIjONm5Ay7toA3qxXSZZcAoIpF0V/Ofd/NnlrI8udk="

before_deploy: ./scripts/install_codesigning_key.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew --info --stacktrace upload closeAndPromoteRepository
  on:
    tags: true
