language: java
install: ./gradlew clean jar
script: ./gradlew check
jdk:
  - oraclejdk8

env:
  global:
    - PGP_KEY_ID="2887CE9B"
    - PGP_PASSWORD=""
    - PGP_SECRET_KEY_RING_FILE=~/.gnupg/secring.gpg
      # NEXUS_USERNAME
    - secure: "Wu9M0ganmgpkBNO1QD4jDHyagWrvm7+2dvNsyDGx9qva2C6xHNVpCtpQ1vFPDTAI76wAv0Yfz8iHVmlMsvJjMfImtip2dVUq+aYK86jEDh4ENfA5uNfjyuTvDRa/cFF+Qm+ml+85IFfWBOo5sCOueX1iKfOsCUETlTjvDCapYkfu728TSnmDGV0R/sNUHi0Mtp4RddWdg4QwOlvqSLBIdh1Y0LFZ1fjQtELcheFZV5MNjXT7t8EbCrqXdu+yaLrr5jm8lNvS+8eMTiZtZ9doUtbiFRbNLc5QAORs4gWo8A3iliCC/wEKNCixa8IlsYM1X1cN77tdSZQwV/zSUutMqwjwYWNl6+BQYPZmGWz1HDIVOhB1b6xiB1C/msLNoQE5OyhqxWGbR18YvqVkwQ3e6kfBw62UlK0CS1ia5mg03GnIyuPQLwOjyYRePmsKyj49MjjmqdZYaU+qoRiOsKRb2+yWjpbOtLcK8SI7a9OdINO+gWQfnPBaiZfRuUClo4Trs6UrJtwiS+5ZdoRsMvuaK/IYPvfCbd3J8ehycjlzDeeCeAs9tICMzGbnfRtgsId4cOAUY6GWoauedPE+3eBVcw1YFZEmcaw1odyzvrR+akiHhPIyM8t1TZogNDZpBUmw0LMEJ1Z32h4acvcX1PKtkiXPMm72tHebR6K43wO1vZ0="
      # NEXUS_PASSWORD
    - secure: "TzVU7JmJmHrLnk0hSowW1KE5E8rB3RF7erhxTN6ei7IjPWnVffE2JQrLXo2jm7aSynxtJyIHio+OgHwKPly3qW3JH/dJlMUVujU3MmxdueVXIXxg4RYxDunigDsXdCahwmJ4Sa7srV/hHEu1uap4Bwfmwq2sDuWtRMGsq0rlwhUGB3dTM2TLccKKF1w5gJNQgtQeEibDQjiDuecLiCxT6KrNL6sByEgVBgJNv/h8YmrY7srFBv5tbruXvXXU4Z1IefUxdQ6s4GcOfkddGmpd1QTLMSJhQSDWx9A6bObtp6pvnX5R2AMKaiFO1rvpswvCGiplJP842I/1AfY4AJJBo702NcAn3LAEUXu00Rj7nHSP6zJ2R5cZ6qmNHRkGmUsl0Q5rDkgKBQeRkVk9UgEDS373DSnIDlSF3VHNJBzyOPxv4+oNMTzv4awzWGEJ+rGe1sliagTvfboYjaGW8JgyJGxVEZmptHmMS1uaiuc8yJ1+cS8J284ZlFzbfQPDev7E9y2J6OhOKXZukADGF/75+3CRg8vWQPAScn2i6Cc2hGOm2FUd2o+uEM76f7XizoufDjM3ftGsQr4cJVQegutJfSH39jdCkb/li1GHVnMme5RXHzF23cL5lN6vFfm7A57PxxiFENFtEjDNPJkves52yH+B0+quOKCbklDU2IU5Nc0="

before_deploy: ./scripts/install_codesigning_key.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew --info --stacktrace upload closeAndPromoteRepository
  on:
    tags: true
